In [15]:
import pandas as pd
from sklearn.impute import KNNImputer
import matplotlib.pyplot as plt
import seaborn as sns


# Define the file path
file_path = '../Datafile Raw/ov_tcga_pan_can_atlas_2018/data_methylation_hm27_hm450_merged.txt'
# Load the data
df = pd.read_csv(file_path, sep="\t", low_memory=False)
df.head()

,ENTITY_STABLE_ID,NAME,DESCRIPTION,TRANSCRIPT_ID,TCGA-04-1331-01,TCGA-04-1332-01,TCGA-04-1335-01,TCGA-04-1336-01,TCGA-04-1337-01,TCGA-04-1338-01,...,TCGA-72-4233-01,TCGA-10-0928-01,TCGA-13-0905-01,TCGA-13-0911-01,TCGA-13-0757-01,TCGA-13-0891-01,TCGA-13-0761-01,TCGA-72-4232-01,TCGA-10-0935-01,TCGA-13-0723-01
0,cg00000292,ATP2A1,1stExon,NM_173201;NM_004320,0.931225,0.527324,0.915472,0.785148,0.893248,0.839604,...,0.918617,0.845659,0.900711,0.833309,0.161915,0.875458,0.922321,0.915103,0.825249,0.792246
1,cg00003994,MEOX2,1stExon,NM_005924,0.047030,0.055236,0.084291,0.112255,0.033616,0.052391,...,0.049666,0.078664,0.595215,0.121275,0.048813,0.184044,0.121193,0.055598,0.682059,0.092517
2,cg00005847,HOXD3,5'UTR,NM_006898,0.810362,0.372304,0.641705,0.749814,0.743525,0.330921,...,0.752913,0.060668,0.923878,0.223114,0.775447,0.072272,0.724261,0.299146,0.443100,0.204097
3,cg00007981,PANX1,1stExon,NM_015368,0.011909,0.008184,0.029346,NaN,0.007378,0.006443,...,0.016528,0.009195,0.005293,0.034475,0.018510,0.019768,0.019488,0.015390,0.014953,0.040380
4,cg00008493,KIAA1409;COX8C,Body;5'UTR,NM_020818;NM_182971,0.942704,0.932735,0.943137,0.940638,0.936440,0.522466,...,0.928889,0.928589,0.958884,0.930258,0.927923,0.931480,0.931972,0.931990,0.927413,0.928525

In [16]:
df=df.transpose()
df

,0,1,2,3,4,5,6,7,8,9,...,22591,22592,22593,22594,22595,22596,22597,22598,22599,22600
ENTITY_STABLE_ID,cg00000292,cg00003994,cg00005847,cg00007981,cg00008493,cg00008713,cg00009407,cg00011459,cg00012199,cg00012386,...,cg27651218,cg27652350,cg27653134,cg27654142,cg27655905,cg27657283,cg27661264,cg27662379,cg27662877,cg27665659
NAME,ATP2A1,MEOX2,HOXD3,PANX1,KIAA1409;COX8C,IMPA2,TTC8,PMM2;TMEM186,ANG;RNASE4,SNAP47;JMJD4,...,KIAA1409;COX8C,ALDH1A3,A2ML1,ZFP2,C11orf24,LEPRE1;C1orf50,GNAS,RPN1,CYB5A,AP1S1
DESCRIPTION,1stExon,1stExon,5'UTR,1stExon,Body;5'UTR,TSS1500,TSS200,Body;TSS1500,TSS1500,Body;TSS200,...,TSS200;5'UTR,Body,Body,1stExon;5'UTR,5'UTR,Body;TSS1500,TSS1500;3'UTR,TSS200,TSS1500,TSS200
TRANSCRIPT_ID,NM_173201;NM_004320,NM_005924,NM_006898,NM_015368,NM_020818;NM_182971,NM_014214,NM_144596;NM_198310;NM_198309,NM_000303;NM_015421,NM_002937;NM_001145,NM_053052;NM_001161465;NM_023007,...,NM_020818;NM_182971,NM_000693,NM_144670,NM_030613,NM_022338,NM_022356;NM_001146289;NM_024097,NM_016592;NM_001077490;NM_080425,NM_002950,NM_001914;NM_148923,NM_001283
TCGA-04-1331-01,0.931225,0.04703,0.810362,0.011909,0.942704,0.054855,0.048007,0.865935,0.03578,0.038247,...,0.940881,0.97275,0.442261,0.036939,0.052637,0.027384,0.087231,0.045186,0.03732,0.043665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-13-0891-01,0.875458,0.184044,0.072272,0.019768,0.93148,0.056492,0.026352,0.932741,0.043264,0.046051,...,0.94281,0.959727,0.045083,0.052652,0.049976,0.019894,0.106503,0.051799,0.052764,0.037789
TCGA-13-0761-01,0.922321,0.121193,0.724261,0.019488,0.931972,0.069129,0.0479,0.707472,0.048506,0.040728,...,0.844734,0.945445,0.352929,0.054608,0.075631,0.057006,0.439695,0.054499,0.071437,0.047014
TCGA-72-4232-01,0.915103,0.055598,0.299146,0.01539,0.93199,0.054592,0.028878,0.914693,0.041026,0.036465,...,0.922683,0.929113,0.521458,0.055219,0.035009,0.02805,0.056355,0.040167,0.038552,0.038873
TCGA-10-0935-01,0.825249,0.682059,0.4431,0.014953,0.927413,0.054845,0.035651,0.869925,0.044026,0.034815,...,0.850027,0.967089,0.424411,0.052973,0.057739,0.017356,0.019558,0.04905,0.048077,0.029426
TCGA-13-0723-01,0.792246,0.092517,0.204097,0.04038,0.928525,0.05845,0.052535,0.867914,0.048611,0.031236,...,0.872836,0.839892,0.849005,0.062214,0.075024,0.021589,0.199704,0.0629,0.055135,0.046203

In [17]:
patient_data = df.copy()  
patient_data = patient_data.drop(index=df.index[[ 2, 3]])
patient_data = patient_data.drop(columns=[patient_data.columns[18351]])

In [18]:
# Define the threshold for missing data (20%)
missing_threshold = 0.1

# Calculate the percentage of missing values for each patient (row)
missing_percentage_per_patient = patient_data.isna().mean(axis=1)

# Get the index of patients with more than 20% missing data
patients_with_high_missing = missing_percentage_per_patient[missing_percentage_per_patient > missing_threshold].index.tolist()

# Print the results
print(f"Total number of patients with more than {missing_threshold*100}% missing data: {len(patients_with_high_missing)}")
print(f"Patients with more than {missing_threshold*100}% or more missing data:")
print(patients_with_high_missing)

Total number of patients with more than 10.0% missing data: 0
Patients with more than 10.0% or more missing data:
[]

In [19]:
# Define the threshold for missing data (80%)
missing_threshold = 0.35

# Calculate the percentage of missing values for each column
missing_percentage_per_column = patient_data.isna().mean()

# Filter columns where missing percentage is ≥ 80%
high_missing_sites = missing_percentage_per_column[missing_percentage_per_column >= missing_threshold].index.tolist()

# Print the CpG sites with 80% or more missing data
print(f"Total CpG sites with at least {missing_threshold*100}% missing data: {len(high_missing_sites)}")
print(f"CpG sites with {missing_threshold*100}% or more missing data:")
print(high_missing_sites)

Total CpG sites with at least 35.0% missing data: 0
CpG sites with 35.0% or more missing data:
[]

In [20]:


# Ensure the first two rows (Stable ID & Gene Name) remain unchanged
stable_id_row = patient_data.iloc[0]  # First row (Stable ID)
gene_name_row = patient_data.iloc[1]  # Second row (Gene Name)

# Extract only patient data (3rd row onwards)
patient_values = patient_data.iloc[2:].copy()

# Initialize KNN Imputer
knn_imputer = KNNImputer(n_neighbors=5)  # You can adjust n_neighbors

# Impute each column separately
for col in patient_values.columns:
    patient_values[[col]] = knn_imputer.fit_transform(patient_values[[col]])

# Reconstruct the full DataFrame
patient_data = pd.concat([stable_id_row.to_frame().T, gene_name_row.to_frame().T, patient_values])

In [21]:
# Check for NaN values in the first row (Stable ID) and second row (Gene Name)
first_row_nan = patient_data.iloc[0].isna().sum()
second_row_nan = patient_data.iloc[1].isna().sum()

# Print results
print(f"🔍 Missing values in the first row (Stable ID): {first_row_nan}")
print(f"🔍 Missing values in the second row (Gene Name): {second_row_nan}")

# Check if any missing values exist
if first_row_nan == 0 and second_row_nan == 0:
    print("✅ No missing values found in the first and second row.")
else:
    print("⚠️ There are missing values in the first or second row.")

🔍 Missing values in the first row (Stable ID): 0
🔍 Missing values in the second row (Gene Name): 132
⚠️ There are missing values in the first or second row.

In [22]:
nan_count = patient_data.isna().sum().sum()

# Print results
if nan_count > 0:
    print(f"The methylation dataset contains {nan_count} missing (NaN) values.")
else:
    print("No missing (NaN) values found in the methylation dataset.")

The methylation dataset contains 132 missing (NaN) values.

In [23]:
# # Extract metadata (first 3 rows) from the original DataFrame
# metadata_rows = df.iloc[:3, :].copy()  # Keep the first three rows

# # Concatenate metadata with the imputed patient data
# final_data = pd.concat([metadata_rows, patient_data_imputed])

final_data=patient_data

In [24]:
final_data

,0,1,2,3,4,5,6,7,8,9,...,22591,22592,22593,22594,22595,22596,22597,22598,22599,22600
ENTITY_STABLE_ID,cg00000292,cg00003994,cg00005847,cg00007981,cg00008493,cg00008713,cg00009407,cg00011459,cg00012199,cg00012386,...,cg27651218,cg27652350,cg27653134,cg27654142,cg27655905,cg27657283,cg27661264,cg27662379,cg27662877,cg27665659
NAME,ATP2A1,MEOX2,HOXD3,PANX1,KIAA1409;COX8C,IMPA2,TTC8,PMM2;TMEM186,ANG;RNASE4,SNAP47;JMJD4,...,KIAA1409;COX8C,ALDH1A3,A2ML1,ZFP2,C11orf24,LEPRE1;C1orf50,GNAS,RPN1,CYB5A,AP1S1
TCGA-04-1331-01,0.931225,0.04703,0.810362,0.011909,0.942704,0.054855,0.048007,0.865935,0.03578,0.038247,...,0.940881,0.97275,0.442261,0.036939,0.052637,0.027384,0.087231,0.045186,0.03732,0.043665
TCGA-04-1332-01,0.527324,0.055236,0.372304,0.008184,0.932735,0.054339,0.050471,0.876822,0.026227,0.024022,...,0.920633,0.828132,0.856183,0.037255,0.051982,0.014439,0.332597,0.046139,0.04535,0.060061
TCGA-04-1335-01,0.915472,0.084291,0.641705,0.029346,0.943137,0.026842,0.077507,0.712961,0.047387,0.027316,...,0.941942,0.951807,0.584416,0.034934,0.055217,0.076347,0.395181,0.04262,0.050956,0.040036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-13-0891-01,0.875458,0.184044,0.072272,0.019768,0.93148,0.056492,0.026352,0.932741,0.043264,0.046051,...,0.94281,0.959727,0.045083,0.052652,0.049976,0.019894,0.106503,0.051799,0.052764,0.037789
TCGA-13-0761-01,0.922321,0.121193,0.724261,0.019488,0.931972,0.069129,0.0479,0.707472,0.048506,0.040728,...,0.844734,0.945445,0.352929,0.054608,0.075631,0.057006,0.439695,0.054499,0.071437,0.047014
TCGA-72-4232-01,0.915103,0.055598,0.299146,0.01539,0.93199,0.054592,0.028878,0.914693,0.041026,0.036465,...,0.922683,0.929113,0.521458,0.055219,0.035009,0.02805,0.056355,0.040167,0.038552,0.038873
TCGA-10-0935-01,0.825249,0.682059,0.4431,0.014953,0.927413,0.054845,0.035651,0.869925,0.044026,0.034815,...,0.850027,0.967089,0.424411,0.052973,0.057739,0.017356,0.019558,0.04905,0.048077,0.029426
TCGA-13-0723-01,0.792246,0.092517,0.204097,0.04038,0.928525,0.05845,0.052535,0.867914,0.048611,0.031236,...,0.872836,0.839892,0.849005,0.062214,0.075024,0.021589,0.199704,0.0629,0.055135,0.046203

In [25]:
# Define the file path
file_path = "../Datafiles Final/Datafiles Cleaned/methylation.pkl"

# Save using Pickle format (best for mixed data types)
final_data.to_pickle(file_path)

print(f"File saved successfully at: {file_path}")

File saved successfully at: ../Datafiles Final/Datafiles Cleaned/methylation.pkl

In [30]:
# Load the Pickle file
df_methylation = pd.read_pickle(file_path)

# Verify the data
df_methylation

,0,1,2,3,4,5,6,7,8,9,...,22591,22592,22593,22594,22595,22596,22597,22598,22599,22600
ENTITY_STABLE_ID,cg00000292,cg00003994,cg00005847,cg00007981,cg00008493,cg00008713,cg00009407,cg00011459,cg00012199,cg00012386,...,cg27651218,cg27652350,cg27653134,cg27654142,cg27655905,cg27657283,cg27661264,cg27662379,cg27662877,cg27665659
NAME,ATP2A1,MEOX2,HOXD3,PANX1,KIAA1409;COX8C,IMPA2,TTC8,PMM2;TMEM186,ANG;RNASE4,SNAP47;JMJD4,...,KIAA1409;COX8C,ALDH1A3,A2ML1,ZFP2,C11orf24,LEPRE1;C1orf50,GNAS,RPN1,CYB5A,AP1S1
TCGA-04-1331-01,0.931225,0.04703,0.810362,0.011909,0.942704,0.054855,0.048007,0.865935,0.03578,0.038247,...,0.940881,0.97275,0.442261,0.036939,0.052637,0.027384,0.087231,0.045186,0.03732,0.043665
TCGA-04-1332-01,0.527324,0.055236,0.372304,0.008184,0.932735,0.054339,0.050471,0.876822,0.026227,0.024022,...,0.920633,0.828132,0.856183,0.037255,0.051982,0.014439,0.332597,0.046139,0.04535,0.060061
TCGA-04-1335-01,0.915472,0.084291,0.641705,0.029346,0.943137,0.026842,0.077507,0.712961,0.047387,0.027316,...,0.941942,0.951807,0.584416,0.034934,0.055217,0.076347,0.395181,0.04262,0.050956,0.040036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-13-0891-01,0.875458,0.184044,0.072272,0.019768,0.93148,0.056492,0.026352,0.932741,0.043264,0.046051,...,0.94281,0.959727,0.045083,0.052652,0.049976,0.019894,0.106503,0.051799,0.052764,0.037789
TCGA-13-0761-01,0.922321,0.121193,0.724261,0.019488,0.931972,0.069129,0.0479,0.707472,0.048506,0.040728,...,0.844734,0.945445,0.352929,0.054608,0.075631,0.057006,0.439695,0.054499,0.071437,0.047014
TCGA-72-4232-01,0.915103,0.055598,0.299146,0.01539,0.93199,0.054592,0.028878,0.914693,0.041026,0.036465,...,0.922683,0.929113,0.521458,0.055219,0.035009,0.02805,0.056355,0.040167,0.038552,0.038873
TCGA-10-0935-01,0.825249,0.682059,0.4431,0.014953,0.927413,0.054845,0.035651,0.869925,0.044026,0.034815,...,0.850027,0.967089,0.424411,0.052973,0.057739,0.017356,0.019558,0.04905,0.048077,0.029426
TCGA-13-0723-01,0.792246,0.092517,0.204097,0.04038,0.928525,0.05845,0.052535,0.867914,0.048611,0.031236,...,0.872836,0.839892,0.849005,0.062214,0.075024,0.021589,0.199704,0.0629,0.055135,0.046203

In [ ]:
#####################################################################################################